# Config file for debugging.
# Use the "--config_file" option to specify the part of this config.

# Change to logging level to DEBUG.
logging:
  root:
    level: DEBUG

# Show module names in the console logging handler.
coloredlogs:
  fmt: "%(asctime)s %(name)-38s %(message)s"