# The path to the file into which the StylesheetData class is serialized
data_file: subreddit_data.yml

# The list of supported file extensions for Reddit Stylesheet Images
image_extensions:
  - .jpg
  - .jpeg
  - .png

# The list of supported image formats for Reddit Stylesheet Images (as defined
# by Pillow)
allowed_image_formats:
  - JPEG
  - PNG

# The maximum file size of Reddit Stylesheet Image
max_image_size: 512000

# The maximum image width of Reddit Stylesheet Image
max_image_width: 16384

# The maximum count of Reddit Stylesheet Images
max_image_count: 50

# The maximum CSS size of Reddit Stylesheet
max_css_size: 102400

# The URL of the W3C CSS Validator
w3c_validator_url: http://jigsaw.w3.org/css-validator/validator

# The path to the output HTML file for the W3C CSS Validator. Output is saved 
# only if errors are found in the CSS
css_validator_output_file: css_validation_result.html

# Logging configuration
logging:
  version: 1
  disable_existing_loggers: false

  formatters:
    detailed:
      format: "%(asctime)s %(name)-25s %(levelname)-7s: %(message)s"

  handlers:   
    file_handler_info:
      class: logging.handlers.RotatingFileHandler
      level: VERBOSE
      filename: default.log
      formatter: detailed
      encoding: utf8
      maxBytes: 10485760 # 10MB
      backupCount: 20

    file_handler_debug:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      filename: default-debug.log
      formatter: detailed
      encoding: utf8
      maxBytes: 10485760 # 10MB
      backupCount: 20

  root:
    level: VERBOSE
    handlers: [file_handler_info, file_handler_debug]
    propagate: yes

# Coloredlogs module configuration
coloredlogs:
  fmt: "%(asctime)s %(message)s"
